### PR TITLE
Add global.export and fix global.location.

### LINKED ISSUE #51: Error with 1.0.0-alpha.4  on Windows
On Windows CMD and GitBash, it seems path seperator often cause some error. 

Test the following code, where `./test.scss` is any given valid `scss` file in the same folder:

```
var sass = require('dart-sass');
var res = sass.renderSync({ file: './test.scss' });
console.log(res);
```

Then got: 

image

In `dart.Uri_parse`‘s body, insert a new line at the begining, `uri = uri.replace(/\\/g, '/')` will work,

So this maybe a problem to be solved.

### PR DESCRIPTION
**Pull request by nex3**
This fixes sass/dart-sass#51.

### CODE REVIEW

**Comment by mbullington** [comment]
Looks good to me, I see a couple minor issues but I'll fix them really quick, thanks!
I'll comment again once it's on pub so you can use it.

File: lib/preamble.dart [hunk 1]
```diff
@@ -1,7 +1,16 @@
...
-  global.location = { href: "file://" + process.cwd() + "/" };
+  // TODO: This isn't really a correct transformation. For example, it will fail
+  // for paths that contain characters that need to be escaped in URLs. Once
+  // dart-lang/sdk#27979 is fixed, it should be possible to make it better.
+  global.location = {
+    href: "file://" + (function() {
+      var cwd = process.cwd();
+      if (process.platform != 'win32') return cwd;
+      return '/' + cwd.replace('\\', '/');
+    }) + "/"
```
Comment (mbullington) [inline lib/preamble.dart:12]: I'm guessing you meant to put a () here? I've fixed this on my own, but I wanted to let you know since you temporarily forked it.

**Comment by mbullington** [comment]
Also, once I looked at the PR locally (I'll admit I only glanced over it on GitHub) I noticed you committed with global.export instead of global.exports, I assume by mistake.

It's all good, but if these were mistakes I'd advise to stop using your fork as soon as possible as it may prevent your code from running entirely on node.js environments.

Thanks for the contribution though!

**Comment by nex3** [comment]
Definitely just dumb mistakes. Luckily I haven't published yet!

**Comment by mbullington** [comment]
It's on pub now as version 1.1.0.

Also, I realized there may be an issue with encapsulating the global variable for the way you're using the preamble. I created issue #2 for it and there should be a way to fix it soon.
